Feature/connect kafka
annaoliinyk/SoftServe-Internship_ETL-project pull request #5
Opened 2022-10-10 16:02 UTC by annaoliinyk

Changes mainly in kafka folder:
- docker-compose.yml -> instructions for kafka setup using docker;
- get_states_OpenSky.py -> with a function that returns a one random state in a form of dictionary with keys id (icao24) and values (all info about a state in form of a list);
- producer.py -> for writing states to a OpenSky_data_ingestion topic
- consumer.py -> for reading data from OpenSky_data_ingestion topic.

2022-10-17 10:06 UTC, annaoliinyk commented
Ready for review

2022-10-27 07:12 UTC, AnnieKey commented on kafka_messenger/consumer.py
> +    def run_consumer(self):
For what purpose is this function?

2022-10-27 07:12 UTC, AnnieKey commented on kafka_messenger/consumer.py
> +        self.consumer = KafkaConsumer(
The same code is in producer. It should be in parent class and inherited.

2022-10-27 07:13 UTC, AnnieKey commented on OpenSkyDataExtractor/get_states.py
> +            states = requests.get("https://opensky-network.org/api/states/all", data=credentials).json()
This link should be in configs file

2022-10-27 07:14 UTC, AnnieKey commented on OpenSkyDataExtractor/get_states.py
> +            states = requests.get("https://opensky-network.org/api/states/all").json()
Same here. Should be in configs file.

2022-10-27 07:17 UTC, AnnieKey commented on definitions.py
> +ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
It should be in the file where you need it

2022-10-27 07:19 UTC, AnnieKey commented on kafka_messenger/data_editor.py
> +class RandomStateExtractor:
Not random states, you need to upload all data in Kafka

2022-10-27 07:20 UTC, AnnieKey commented on kafka_messenger/get_states_OpenSky.py
> +STATE_DICT_KEYS = ['icao24', 'values']
Should be in config file

2022-10-27 07:20 UTC, AnnieKey commented on kafka_messenger/get_states_OpenSky.py
> +        states_dict = data_ingestion_obj.get_states()
There is code duplication here

2022-10-27 07:21 UTC, AnnieKey commented on kafka_messenger/producer.py
> +
There should be no space

2022-10-27 07:21 UTC, AnaKovaGH commented on kafka_messenger/producer.py
> +        self.producer = KafkaProducer(
Same as in producer

2022-10-27 07:22 UTC, AnnieKey requested changes
Please change what was commented

2022-10-27 12:24 UTC, AnnieKey commented on main.py
> +from kafka_messenger import producer, consumer
Move to kafka imports sections

2022-10-27 12:27 UTC, AnnieKey commented on main.py
>      end_timestamp = datetime.now().timestamp()
Move to the end of the program

2022-10-27 12:32 UTC, AnnieKey commented on main.py
> +        consumer.MyConsumer()
How it should work?

2022-10-27 12:38 UTC, AnnieKey commented on main.py
> +        producer.MyProducer().send_all_states(data_ingestion_obj)
Rewrite is without second data ingestion

2022-10-27 12:39 UTC, AnnieKey requested changes
Please review comments and rename all variables and class's names to be more readable

2022-10-28 11:20 UTC, annaoliinyk commented
Ready for review

2022-10-28 12:06 UTC, AnnieKey approved these changes
LGTM!

2022-10-28 12:53 UTC, merged